const usersData = [
  {
    id: 1,
    firstName: "Emily",
    lastName: "Johnson",
    age: 29,
    gender: "female",
    email: "quiethoursemily1@example.com",
    password: "emily320pass",
    username: "quiet.hours.emily",
    birthDate: "1997-05-05",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    bio: "Finding little moments worth remembering ✨ | Austin",
    postImage: "https://picsum.photos/id/1015/800/800",
    postCaption: "A quiet moment in a beautiful place.",
    storyImage: "https://picsum.photos/id/1060/500/900",
    likes: 12589,
    comments: 434
  },
  {
    id: 2,
    firstName: "Arjun",
    lastName: "Mehta",
    age: 30,
    gender: "male",
    email: "arjunonthemove2@example.com",
    password: "arjun370pass",
    username: "arjun.onthemove",
    birthDate: "1996-06-20",
    image: "https://randomuser.me/api/portraits/men/82.jpg",
    bio: "Chasing sunsets and stamps in my passport ✈️ | Mumbai",
    postImage: "https://picsum.photos/id/1016/800/800",
    postCaption: "Chasing quiet mornings above the clouds.",
    storyImage: "https://picsum.photos/id/1061/500/900",
    likes: 13303,
    comments: 1330
  },
  {
    id: 3,
    firstName: "Sofia",
    lastName: "Ricci",
    age: 21,
    gender: "female",
    email: "wearitwellsofia3@example.com",
    password: "sofia949pass",
    username: "wearitwell.sofia",
    birthDate: "2005-09-10",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    bio: "Style is a way to say who you are without speaking 👗 | Milan",
    postImage: "https://picsum.photos/id/1018/800/800",
    postCaption: "Old streets, new outfit.",
    storyImage: "https://picsum.photos/id/1062/500/900",
    likes: 10379,
    comments: 334
  },
  {
    id: 4,
    firstName: "Liam",
    lastName: "O'Connor",
    age: 26,
    gender: "male",
    email: "liamgaragedays4@example.com",
    password: "liam975pass",
    username: "liam.garage.days",
    birthDate: "2000-05-03",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    bio: "Horsepower and open roads 🏎️ | Dublin",
    postImage: "https://picsum.photos/id/1019/800/800",
    postCaption: "Late-night drives hit different.",
    storyImage: "https://picsum.photos/id/1063/500/900",
    likes: 3894,
    comments: 278
  },
  {
    id: 5,
    firstName: "Priya",
    lastName: "Nair",
    age: 24,
    gender: "female",
    email: "spoonfulspriya5@example.com",
    password: "priya314pass",
    username: "spoonfuls.priya",
    birthDate: "2002-06-12",
    image: "https://randomuser.me/api/portraits/women/28.jpg",
    bio: "Home cook turned kitchen wanderer 🍲 | Bengaluru",
    postImage: "https://picsum.photos/id/1020/800/800",
    postCaption: "Comfort in every bite.",
    storyImage: "https://picsum.photos/id/1064/500/900",
    likes: 11060,
    comments: 442
  },
  {
    id: 6,
    firstName: "Noah",
    lastName: "Bergström",
    age: 24,
    gender: "male",
    email: "noahframedby6@example.com",
    password: "noah376pass",
    username: "noah.framed.by",
    birthDate: "2002-08-13",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
    bio: "Framing the world one shot at a time 📸 | Stockholm",
    postImage: "https://picsum.photos/id/1021/800/800",
    postCaption: "Light does all the talking.",
    storyImage: "https://picsum.photos/id/1065/500/900",
    likes: 10565,
    comments: 480
  },
  {
    id: 7,
    firstName: "Mia",
    lastName: "Tanaka",
    age: 29,
    gender: "female",
    email: "tailwagginmia7@example.com",
    password: "mia167pass",
    username: "tailwaggin.mia",
    birthDate: "1997-07-09",
    image: "https://randomuser.me/api/portraits/women/30.jpg",
    bio: "Dog mom first, everything else second 🐾 | Tokyo",
    postImage: "https://picsum.photos/id/1022/800/800",
    postCaption: "Best days start with wet-nose kisses.",
    storyImage: "https://picsum.photos/id/1067/500/900",
    likes: 3536,
    comments: 126
  },
  {
    id: 8,
    firstName: "Ethan",
    lastName: "Walker",
    age: 33,
    gender: "male",
    email: "ethangrindmode8@example.com",
    password: "ethan242pass",
    username: "ethan.grindmode",
    birthDate: "1993-03-09",
    image: "https://randomuser.me/api/portraits/men/95.jpg",
    bio: "Built one rep at a time 💪 | Denver",
    postImage: "https://picsum.photos/id/1023/800/800",
    postCaption: "Sweat now, smile later.",
    storyImage: "https://picsum.photos/id/1068/500/900",
    likes: 4120,
    comments: 171
  },
  {
    id: 9,
    firstName: "Isabella",
    lastName: "Santos",
    age: 26,
    gender: "female",
    email: "roamoftenisabella9@example.com",
    password: "isabella605pass",
    username: "roam.often.isabella",
    birthDate: "2000-03-17",
    image: "https://randomuser.me/api/portraits/women/65.jpg",
    bio: "Collecting cities, not things 🌍 | Lisbon",
    postImage: "https://picsum.photos/id/1024/800/800",
    postCaption: "Got lost on purpose today.",
    storyImage: "https://picsum.photos/id/1069/500/900",
    likes: 1569,
    comments: 142
  },
  {
    id: 10,
    firstName: "Lucas",
    lastName: "Müller",
    age: 38,
    gender: "male",
    email: "lucascodeandcoffee10@example.com",
    password: "lucas490pass",
    username: "lucas.codeandcoffee",
    birthDate: "1988-02-13",
    image: "https://randomuser.me/api/portraits/men/36.jpg",
    bio: "Building things that (mostly) work 💻 | Berlin",
    postImage: "https://picsum.photos/id/1025/800/800",
    postCaption: "Debugging life, one line at a time.",
    storyImage: "https://picsum.photos/id/1070/500/900",
    likes: 9843,
    comments: 266
  },
  {
    id: 11,
    firstName: "Ava",
    lastName: "Thompson",
    age: 36,
    gender: "female",
    email: "greenhorizonava11@example.com",
    password: "ava756pass",
    username: "greenhorizon.ava",
    birthDate: "1990-05-25",
    image: "https://randomuser.me/api/portraits/women/78.jpg",
    bio: "Wandering wherever the trail leads 🌲 | Portland",
    postImage: "https://picsum.photos/id/1035/800/800",
    postCaption: "Trees taller than my worries.",
    storyImage: "https://picsum.photos/id/1071/500/900",
    likes: 5653,
    comments: 376
  },
  {
    id: 12,
    firstName: "Kabir",
    lastName: "Sharma",
    age: 19,
    gender: "male",
    email: "kabirurbanframe12@example.com",
    password: "kabir369pass",
    username: "kabir.urbanframe",
    birthDate: "2007-12-24",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    bio: "City lights, quiet corners 🏙️ | Delhi",
    postImage: "https://picsum.photos/id/1036/800/800",
    postCaption: "The city never stops talking.",
    storyImage: "https://picsum.photos/id/1072/500/900",
    likes: 8281,
    comments: 435
  },
  {
    id: 13,
    firstName: "Chloe",
    lastName: "Bennett",
    age: 23,
    gender: "female",
    email: "brewnoteschloe13@example.com",
    password: "chloe265pass",
    username: "brewnotes.chloe",
    birthDate: "2003-06-25",
    image: "https://randomuser.me/api/portraits/women/72.jpg",
    bio: "Powered by espresso and good playlists ☕ | Seattle",
    postImage: "https://picsum.photos/id/1037/800/800",
    postCaption: "Mornings taste better like this.",
    storyImage: "https://picsum.photos/id/1073/500/900",
    likes: 8917,
    comments: 1114
  },
  {
    id: 14,
    firstName: "Rohan",
    lastName: "Kapoor",
    age: 30,
    gender: "male",
    email: "rohanchromeandoil14@example.com",
    password: "rohan159pass",
    username: "rohan.chrome.and.oil",
    birthDate: "1996-05-08",
    image: "https://randomuser.me/api/portraits/men/29.jpg",
    bio: "Weekend garage, weekday grind 🔧 | Pune",
    postImage: "https://picsum.photos/id/1040/800/800",
    postCaption: "Some things run better on chrome.",
    storyImage: "https://picsum.photos/id/1074/500/900",
    likes: 4026,
    comments: 309
  },
  {
    id: 15,
    firstName: "Zoe",
    lastName: "Nguyen",
    age: 36,
    gender: "female",
    email: "threadtheoryzoe15@example.com",
    password: "zoe775pass",
    username: "thread.theory.zoe",
    birthDate: "1990-03-05",
    image: "https://randomuser.me/api/portraits/women/26.jpg",
    bio: "Thrifted finds, big dreams 🧵 | Ho Chi Minh City",
    postImage: "https://picsum.photos/id/1041/800/800",
    postCaption: "Vintage never really goes out of style.",
    storyImage: "https://picsum.photos/id/1075/500/900",
    likes: 7867,
    comments: 437
  },
  {
    id: 16,
    firstName: "Daniel",
    lastName: "Kim",
    age: 36,
    gender: "male",
    email: "danielpassportfull16@example.com",
    password: "daniel305pass",
    username: "daniel.passportfull",
    birthDate: "1990-12-23",
    image: "https://randomuser.me/api/portraits/men/18.jpg",
    bio: "Backpack heavier than my plans 🎒 | Seoul",
    postImage: "https://picsum.photos/id/1042/800/800",
    postCaption: "Somewhere between here and nowhere.",
    storyImage: "https://picsum.photos/id/1076/500/900",
    likes: 11760,
    comments: 435
  },
  {
    id: 17,
    firstName: "Amara",
    lastName: "Okafor",
    age: 35,
    gender: "female",
    email: "gentlelifeamara17@example.com",
    password: "amara353pass",
    username: "gentlelife.amara",
    birthDate: "1991-08-04",
    image: "https://randomuser.me/api/portraits/women/92.jpg",
    bio: "Soft life, loud dreams 🌸 | Lagos",
    postImage: "https://picsum.photos/id/1043/800/800",
    postCaption: "Slow mornings, full heart.",
    storyImage: "https://picsum.photos/id/1077/500/900",
    likes: 3761,
    comments: 313
  },
  {
    id: 18,
    firstName: "Marco",
    lastName: "Bianchi",
    age: 19,
    gender: "male",
    email: "marcofedwell18@example.com",
    password: "marco746pass",
    username: "marco.fedwell",
    birthDate: "2007-02-23",
    image: "https://randomuser.me/api/portraits/men/14.jpg",
    bio: "Pizza is a love language 🍕 | Naples",
    postImage: "https://picsum.photos/id/1044/800/800",
    postCaption: "Made with too much garlic, not sorry.",
    storyImage: "https://picsum.photos/id/1078/500/900",
    likes: 1044,
    comments: 47
  },
  {
    id: 19,
    firstName: "Riya",
    lastName: "Iyer",
    age: 35,
    gender: "female",
    email: "framedbyriya19@example.com",
    password: "riya785pass",
    username: "framed.by.riya",
    birthDate: "1991-04-09",
    image: "https://randomuser.me/api/portraits/women/84.jpg",
    bio: "Chasing golden hour every single day 🌅 | Chennai",
    postImage: "https://picsum.photos/id/1045/800/800",
    postCaption: "Some skies deserve a second look.",
    storyImage: "https://picsum.photos/id/1079/500/900",
    likes: 8033,
    comments: 382
  },
  {
    id: 20,
    firstName: "Jack",
    lastName: "Sullivan",
    age: 34,
    gender: "male",
    email: "jacktideline20@example.com",
    password: "jack196pass",
    username: "jack.tideline",
    birthDate: "1992-07-07",
    image: "https://randomuser.me/api/portraits/men/87.jpg",
    bio: "Salt water fixes everything 🏄 | Sydney",
    postImage: "https://picsum.photos/id/1047/800/800",
    postCaption: "Paddled out before the world woke up.",
    storyImage: "https://picsum.photos/id/1080/500/900",
    likes: 1668,
    comments: 47
  },
  {
    id: 21,
    firstName: "Elena",
    lastName: "Popescu",
    age: 20,
    gender: "female",
    email: "stepbystepelena21@example.com",
    password: "elena761pass",
    username: "stepbystep.elena",
    birthDate: "2006-11-21",
    image: "https://randomuser.me/api/portraits/women/90.jpg",
    bio: "Movement is my mother tongue 💃 | Bucharest",
    postImage: "https://picsum.photos/id/1049/800/800",
    postCaption: "Every step tells a small story.",
    storyImage: "https://picsum.photos/id/1081/500/900",
    likes: 1692,
    comments: 153
  },
  {
    id: 22,
    firstName: "Omar",
    lastName: "Farouk",
    age: 26,
    gender: "male",
    email: "omarstructuretales22@example.com",
    password: "omar649pass",
    username: "omar.structuretales",
    birthDate: "2000-04-07",
    image: "https://randomuser.me/api/portraits/men/70.jpg",
    bio: "Obsessed with lines, light and old stone 🕌 | Cairo",
    postImage: "https://picsum.photos/id/1050/800/800",
    postCaption: "Symmetry has a way of calming me.",
    storyImage: "https://picsum.photos/id/1082/500/900",
    likes: 7430,
    comments: 464
  },
  {
    id: 23,
    firstName: "Grace",
    lastName: "Mitchell",
    age: 26,
    gender: "female",
    email: "whiskersdiarygrace23@example.com",
    password: "grace927pass",
    username: "whiskersdiary.grace",
    birthDate: "2000-02-15",
    image: "https://randomuser.me/api/portraits/women/70.jpg",
    bio: "Two cats, zero regrets 🐱 | Melbourne",
    postImage: "https://picsum.photos/id/1051/800/800",
    postCaption: "Naps: an expert-level hobby.",
    storyImage: "https://picsum.photos/id/1083/500/900",
    likes: 14192,
    comments: 1013
  },
  {
    id: 24,
    firstName: "Diego",
    lastName: "Fernandez",
    age: 26,
    gender: "male",
    email: "diegochordnotes24@example.com",
    password: "diego597pass",
    username: "diego.chordnotes",
    birthDate: "2000-03-14",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
    bio: "Chords, chaos and coffee 🎸 | Buenos Aires",
    postImage: "https://picsum.photos/id/1052/800/800",
    postCaption: "Wrote this one at 2am, don't judge.",
    storyImage: "https://picsum.photos/id/1084/500/900",
    likes: 7966,
    comments: 379
  },
  {
    id: 25,
    firstName: "Hana",
    lastName: "Yoshida",
    age: 19,
    gender: "female",
    email: "roamoftenhana25@example.com",
    password: "hana902pass",
    username: "roam.often.hana",
    birthDate: "2007-07-09",
    image: "https://randomuser.me/api/portraits/women/54.jpg",
    bio: "Slow travel, deep breaths 🍃 | Kyoto",
    postImage: "https://picsum.photos/id/1053/800/800",
    postCaption: "Found stillness between two temples.",
    storyImage: "https://picsum.photos/id/1003/500/900",
    likes: 12943,
    comments: 349
  },
  {
    id: 26,
    firstName: "Felix",
    lastName: "Andersen",
    age: 25,
    gender: "male",
    email: "felixchromeandoil26@example.com",
    password: "felix159pass",
    username: "felix.chrome.and.oil",
    birthDate: "2001-05-07",
    image: "https://randomuser.me/api/portraits/men/76.jpg",
    bio: "Restoring old engines, one bolt at a time 🔩 | Oslo",
    postImage: "https://picsum.photos/id/1054/800/800",
    postCaption: "Patience looks good in chrome.",
    storyImage: "https://picsum.photos/id/1004/500/900",
    likes: 9569,
    comments: 869
  },
  {
    id: 27,
    firstName: "Layla",
    lastName: "Hassan",
    age: 35,
    gender: "female",
    email: "closetnoteslayla27@example.com",
    password: "layla158pass",
    username: "closet.notes.layla",
    birthDate: "1991-09-06",
    image: "https://randomuser.me/api/portraits/women/29.jpg",
    bio: "Minimal wardrobe, maximum intention 🤍 | Dubai",
    postImage: "https://picsum.photos/id/1055/800/800",
    postCaption: "Less noise, more style.",
    storyImage: "https://picsum.photos/id/1005/500/900",
    likes: 8400,
    comments: 646
  },
  {
    id: 28,
    firstName: "Ivan",
    lastName: "Petrov",
    age: 31,
    gender: "male",
    email: "ivangrindmode28@example.com",
    password: "ivan352pass",
    username: "ivan.grindmode",
    birthDate: "1995-02-19",
    image: "https://randomuser.me/api/portraits/men/55.jpg",
    bio: "Cold mornings, hot workouts ❄️ | Moscow",
    postImage: "https://picsum.photos/id/1056/800/800",
    postCaption: "Discipline before motivation, always.",
    storyImage: "https://picsum.photos/id/1006/500/900",
    likes: 9565,
    comments: 956
  },
  {
    id: 29,
    firstName: "Nadia",
    lastName: "Rossi",
    age: 25,
    gender: "female",
    email: "kitchentalesnadia29@example.com",
    password: "nadia421pass",
    username: "kitchen.tales.nadia",
    birthDate: "2001-11-23",
    image: "https://randomuser.me/api/portraits/women/58.jpg",
    bio: "Pasta first, questions later 🍝 | Rome",
    postImage: "https://picsum.photos/id/1057/800/800",
    postCaption: "Sunday sauce, no rules broken.",
    storyImage: "https://picsum.photos/id/1008/500/900",
    likes: 3990,
    comments: 166
  },
  {
    id: 30,
    firstName: "Caleb",
    lastName: "Foster",
    age: 29,
    gender: "male",
    email: "calebamongtrees30@example.com",
    password: "caleb569pass",
    username: "caleb.among.trees",
    birthDate: "1997-02-01",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    bio: "Mountains are my therapy ⛰️ | Vancouver",
    postImage: "https://picsum.photos/id/1058/800/800",
    postCaption: "Silence sounds better up here.",
    storyImage: "https://picsum.photos/id/1009/500/900",
    likes: 10257,
    comments: 732
  }
];

export default usersData;