const reelsData = [
  {
    id: 1,
    videoUrl: "https://assets.mixkit.co/videos/51502/51502-360.mp4",
    caption: "Overhead view of a rocky coast and waves crashing",
    username: "aarav.explores",
    profileUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    likes: 15420,
    comments: 342,
    shares: 128,
  },
  {
    id: 2,
    videoUrl: "https://assets.mixkit.co/huqnk4h26ril4hpbfz2k40paxd76",
    caption: "Water droplets on a green bush",
    username: "priya.greenlens",
    profileUrl: "https://randomuser.me/api/portraits/women/44.jpg",
    likes: 8210,
    comments: 156,
    shares: 64,
  },
  {
    id: 3,
    videoUrl: "https://assets.mixkit.co/videos/51501/51501-360.mp4",
    caption: "Flying over a green mangrove swamp",
    username: "rohan.aerials",
    profileUrl: "https://randomuser.me/api/portraits/men/15.jpg",
    likes: 22890,
    comments: 501,
    shares: 302,
  },
  {
    id: 4,
    videoUrl: "https://assets.mixkit.co/videos/51500/51500-360.mp4",
    caption: "Aerial view of turquoise waves on a sand beach",
    username: "sana.beachdiaries",
    profileUrl: "https://randomuser.me/api/portraits/women/68.jpg",
    likes: 34120,
    comments: 890,
    shares: 445,
  },
  {
    id: 5,
    videoUrl: "https://assets.mixkit.co/61aiuz054t613hexpz0a44z55ctu",
    caption: "Droplets falling on a tulip",
    username: "kabir.macroshots",
    profileUrl: "https://randomuser.me/api/portraits/men/51.jpg",
    likes: 6720,
    comments: 98,
    shares: 40,
  },
  {
    id: 6,
    videoUrl: "https://assets.mixkit.co/videos/52284/52284-360.mp4",
    caption: "Blazing flames over a black backdrop",
    username: "ishaan.fireedits",
    profileUrl: "https://randomuser.me/api/portraits/men/77.jpg",
    likes: 45300,
    comments: 1230,
    shares: 720,
  },
  {
    id: 7,
    videoUrl: "https://assets.mixkit.co/videos/51506/51506-360.mp4",
    caption: "Aerial view of sea waves crashing on a rock",
    username: "meera.oceanviews",
    profileUrl: "https://randomuser.me/api/portraits/women/21.jpg",
    likes: 12980,
    comments: 267,
    shares: 110,
  },
  {
    id: 8,
    videoUrl: "https://assets.mixkit.co/f27a1b0vj3f6b3zd5s88lhwabc8l",
    caption: "Water splash on orchid petals",
    username: "ananya.florals",
    profileUrl: "https://randomuser.me/api/portraits/women/57.jpg",
    likes: 5430,
    comments: 76,
    shares: 29,
  },
  {
    id: 9,
    videoUrl: "https://assets.mixkit.co/videos/1968/1968-360.mp4",
    caption: "Black background with smoke foreground",
    username: "dev.moodyvisuals",
    profileUrl: "https://randomuser.me/api/portraits/men/9.jpg",
    likes: 18760,
    comments: 402,
    shares: 190,
  },
  {
    id: 10,
    videoUrl: "https://assets.mixkit.co/jobnb0prcewa9fqciuzyhy2orxiv",
    caption: "Water drops falling on flowers",
    username: "nisha.petalsnpixels",
    profileUrl: "https://randomuser.me/api/portraits/women/12.jpg",
    likes: 7340,
    comments: 112,
    shares: 51,
  },
  {
    id: 11,
    videoUrl: "https://assets.mixkit.co/videos/28901/28901-360.mp4",
    caption: "Sand falling from an hourglass on black background",
    username: "arjun.timelapses",
    profileUrl: "https://randomuser.me/api/portraits/men/63.jpg",
    likes: 26540,
    comments: 610,
    shares: 275,
  },
  {
    id: 12,
    videoUrl: "https://assets.mixkit.co/videos/51505/51505-360.mp4",
    caption: "Foaming waves on the shore of a beach",
    username: "riya.tidesnwaves",
    profileUrl: "https://randomuser.me/api/portraits/women/85.jpg",
    likes: 19870,
    comments: 388,
    shares: 205,
  },
  {
    id: 13,
    videoUrl: "https://assets.mixkit.co/videos/10428/10428-360.mp4",
    caption: "Serving fresh orange juice in a glass",
    username: "vikram.foodfix",
    profileUrl: "https://randomuser.me/api/portraits/men/40.jpg",
    likes: 9820,
    comments: 203,
    shares: 88,
  },
  {
    id: 14,
    videoUrl: "https://assets.mixkit.co/videos/3463/3463-360.mp4",
    caption: "Sparks of fire on a black background",
    username: "tanvi.sparkstudio",
    profileUrl: "https://randomuser.me/api/portraits/women/29.jpg",
    likes: 31200,
    comments: 704,
    shares: 350,
  },
  {
    id: 15,
    videoUrl: "https://assets.mixkit.co/qi90kl6bw08frnw8zklcpfyzzowk",
    caption: "Droplets on a red rose",
    username: "yash.rosegarden",
    profileUrl: "https://randomuser.me/api/portraits/men/24.jpg",
    likes: 11230,
    comments: 189,
    shares: 77,
  },
  {
    id: 16,
    videoUrl: "https://assets.mixkit.co/videos/3458/3458-360.mp4",
    caption: "Candle lighting in the dark",
    username: "simran.candleglow",
    profileUrl: "https://randomuser.me/api/portraits/women/6.jpg",
    likes: 14560,
    comments: 298,
    shares: 132,
  },
  {
    id: 17,
    videoUrl:
      "https://assets.mixkit.co/active_storage/video_items/100177/1721167467/100177-video-360.mp4",
    caption: "Birds soaring above a rocky cliff and green foliage",
    username: "kunal.wildwings",
    profileUrl: "https://randomuser.me/api/portraits/men/88.jpg",
    likes: 27650,
    comments: 615,
    shares: 298,
  },
  {
    id: 18,
    videoUrl: "https://assets.mixkit.co/7d3euln25fvfgpiccc87km00geyp",
    caption: "Modern office buildings reflecting on a lake",
    username: "neha.cityscapes",
    profileUrl: "https://randomuser.me/api/portraits/women/33.jpg",
    likes: 6980,
    comments: 87,
    shares: 33,
  },
];
 
export default reelsData;
 